apiVersion: batch/v1
kind: Job
metadata:
  name: create-supervisor
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
          - name: create-supervisor
            image: theithollow/hollowapp-blog:curl
            volumeMounts:
            - name: supervisor-config-volume
              mountPath: /app/supervisor-spec.json
              subPath: supervisor-spec.json
            args:
            - /bin/sh
            - -c
            - "curl -X POST -H 'Content-Type: application/json' -d @/app/supervisor-spec.json http://signoz-druid-router:8888/druid/indexer/v1/supervisor"
      volumes:
          - name: supervisor-config-volume
            configMap:
              name: supervisor-config
      restartPolicy: Never
  backoffLimit: 4