on:
  pull_request:

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  PR_NUMBER: ${{ github.event.number }}
jobs:
  comment_on_pr:
    name: PR comment
    runs-on: ubuntu-latest
    steps:
      - name: Check ENV
        run: echo $GITHUB_ACCESS_TOKEN
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          repository: signoz-bot/drudgery
      - name: Use Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Setup Cache & Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile
      - name: Comment on PR
        run: node pr-comment.js
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

